# Generated by Django 6.0.3 on 2026-04-05 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_vocab', models.CharField(help_text='The word or expression to practice', max_length=255, unique=True)),
                ('language', models.TextField(help_text="The language of the word (e.g., 'English', 'Spanish')", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True, help_text='Whether this word is available for practice')),
            ],
        ),
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_count', models.PositiveIntegerField(default=0, help_text='Number of times the user has practiced this word')),
                ('last_practiced', models.DateTimeField(blank=True, help_text='Last time the user practiced this word', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True, help_text='Whether this user-word association is active')),
                ('user', models.ForeignKey(help_text='The user practicing this word', on_delete=django.db.models.deletion.CASCADE, related_name='words_vocab', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(help_text='The vocabulary word being practiced', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='apps_language_practice.vocabulary')),
            ],
            options={
                'verbose_name': 'User Vocabulary',
                'verbose_name_plural': 'Users Vocabulary',
                'unique_together': {('user', 'vocabulary')},
            },
        ),
    ]
