# Generated by Django 6.0.3 on 2026-06-02 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_language_practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The language (e.g., 'English', 'Spanish')", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True, help_text='Whether this word is available for practice')),
            ],
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='language',
            field=models.ForeignKey(help_text="The language (e.g., 'English', 'Spanish')", on_delete=django.db.models.deletion.CASCADE, to='apps_language_practice.language'),
        ),
    ]
