# Generated by Django 6.0.3 on 2026-10-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_language_practice', '0002_language_alter_vocabulary_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='word_vocab',
            field=models.CharField(help_text='The word or expression to practice', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together={('word_vocab', 'language')},
        ),
    ]
