FROM python:3.14-slim
COPY --from=docker.io/astral/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update -y && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    nano \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y

COPY .. /app/

RUN uv sync

EXPOSE 8000