FROM ghcr.io/astral-sh/uv:debian-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update -y && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    nano \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y

COPY .. /app/

EXPOSE 8000