from django.utils import timezone

from django.db import models


class ChatAI(models.Model):    
    conversation_id = models.CharField(max_length=100, blank=False, null=False, help_text="Unique identifier for the conversation")
    user_message = models.TextField(blank=False, null=False, help_text="The message content sent by the user")
    ai_message = models.TextField(blank=False, null=False, help_text="The message content generated by the AI in response")
    llm_model = models.CharField(max_length=100, blank=False, null=False, help_text="The language model used for the conversation (e.g., 'gpt-3.5-turbo')")
    input_tokens = models.PositiveIntegerField(default=0, help_text="Number of tokens used as input to the model")
    output_tokens = models.PositiveIntegerField(default=0, help_text="Number of tokens generated by the model in response")
    latency = models.FloatField(default=0.0, help_text="Time taken for the model to process and generate a response in seconds")
    other_attributes = models.JSONField(blank=True, null=True, help_text="Any additional attributes related to the conversation")
    created_at = models.DateTimeField(auto_now_add=True, help_text="Timestamp when the message was created")

    def __str__(self):
        return f"{self.conversation_id} - {self.message[:50]}"