# Generated by Django 6.0.3 on 2026-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(help_text='Unique identifier for the conversation', max_length=100)),
                ('user_message', models.TextField(help_text='The message content sent by the user')),
                ('ai_message', models.TextField(help_text='The message content generated by the AI in response')),
                ('llm_model', models.CharField(help_text="The language model used for the conversation (e.g., 'gpt-3.5-turbo')", max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Number of tokens used as input to the model')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Number of tokens generated by the model in response')),
                ('latency', models.FloatField(default=0.0, help_text='Time taken for the model to process and generate a response in seconds')),
                ('other_attributes', models.JSONField(blank=True, help_text='Any additional attributes related to the conversation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was created')),
            ],
        ),
    ]
