# Generated by Django 6.0.3 on 2026-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_authentication', '0002_rename_staff_user_is_staff_remove_user_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keep_sending_taks',
            field=models.BooleanField(default=True, help_text='Whether to keep sending practice words via email'),
        ),
    ]
